// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://shxkkiyxcivdjiznyzqe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNoeGtraXl4Y2l2ZGppem55enFlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg4NTQ4NTMsImV4cCI6MjA3NDQzMDg1M30.jWHikisz32tZ-kpTTaqd-GCzpI-Vy3C7fcqx-utFuus";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});